### ISSUE TITLE
How to test an object?

### ISSUE THREAD

**Issue by yangyixiaof** [psycopaths/jdart#11]
I have an Object named 'md' in the field of my test class, I want to make it and its fields both symbolic. The Object 'md' has two fields which are named 'id' and 'jd' respectively. 'id' and 'jd' are both of primitive type int.
However, when I config as follows:

jdart.configs.cm1analysis.symbolic.include=this.md

I found 'md' is symbolic, but the fields of 'md' are not symbolic.
Here is information shown in the command line: 

[FINEST] processing primitive field this.md.id, force: false, makeSymbolic: false

Is there any way to make the field of the field of an Object be forced to be symbolic?
The two fields 'id' and 'jd' are public in Object 'md'.

What is more, when I refer to the field of 'md' by method, for example: using 'md.getId() > 10' instead of 'md.id > 10', JDart seems not working properly?

my test class is shown below:
`
public class MArrayTest {
	
	int[] arr = {1, 2, 3, 4};
	MData md = new MData();
	
	public void TestArrayIndex(int i) throws Exception
	{
		if (arr[i] > 3)
		{
			System.err.println("errors happen.");
			throw new Exception("some strange errors happen.");
		}
		if (md.getId() > 10)
		{
			System.err.println("Ha Ha!");
		}
		System.err.println("i");
	}
	
	public static void main(String[] args) {
		MArrayTest mat = new MArrayTest();
		try {
			mat.TestArrayIndex(0);
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
	
}
`

The type of 'md' which is of name 'MData' is shown below:

`
import java.util.HashMap;

public class MData {
	
	public int id=0;
	public int jd=0;
	// HashMap<String, String> hm = new HashMap<String, String>();
	
	public MData() {
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getJd() {
		return jd;
	}

	public void setJd(int jd) {
		this.jd = jd;
	}
	
}
`

The configuration file is shown below:

`
@using = jpf-jdart
shell=gov.nasa.jpf.jdart.JDart
symbolic.dp=z3
symbolic.dp.z3.bitvectors=true
log.finest=jdart
log.info=constraints

classpath=target/classes

target=MArrayTest
concolic.method.cm1=MArrayTest.TestArrayIndex(i:int)
concolic.method.cm1.config=cm1analysis
jdart.configs.cm1analysis.symbolic.include=this.md
concolic.method=cm1
`

Besides, I want to ask another question: "Does the jpf configuration 'classpath' still hold the same meaning in jdart?"

**Comment by fhowar** [comment]
Hi, I read the message and will manage to look it tomorrow hopefully

**Comment by ksluckow** [comment]
Sorry, I didn't see your question before now.
Do you want to just have the fields `id` and `jd` of `MData` symbolic? If that is the case, then replace your symbolic field spec with:
```
jdart.configs.cm1analysis.symbolic.include=this.md*
```

Regarding your second question: Yes, the classpath variable in JDart means the same as in jpf-core.

**Comment by yangyixiaof** [comment]
It does work, very thanks!
