### ISSUE TITLE
How to generate JUnit test cases and Coverage report from JDart.

### ISSUE THREAD

**Issue by srgiri** [psycopaths/jdart#22]
Hi,
 I am able to get the test cases printed on the console. But I don't know what configuration I should make in jpf file so that I can get the JUnit test cases and the coverage report.
Please guide me.

Regards,
S R Giri

**Comment by ksluckow** [comment]
Hi!

You can put `jdart.tests.gen=true` in your jpf config file. This will generate a JUnit test suite based on the explored paths.
Additional options (please see class `gov.nasa.jpf.jdart.testsuites.TestSuiteGenerator`):
`jdart.tests.dir`: output dir of test suite
`jdart.tests.pkg`: package name of test suite
`jdart.tests.suitename`: (optional) class name of test suite

To obtain a coverage report, you can use a tool like JaCoCo when you run the test suite or you can make use of JPF's coverage component, which can be enabled with:
```
listener=gov.nasa.jpf.listener.CoverageAnalyzer

coverage.include = <<list of class names here>>
coverage.show_methods = true
```
Please check out `jpf-core` for more details on the `CoverageAnalyzer`!

**Comment by srgiri** [comment]
Thank you very much. It worked.

**Comment by srgiri** [comment]
Hi,
  It worked fine for normal data types. But it doesn't generate correct method call where method takes a custom class object as argument (in the _testcase.java_ file). The method is invoked with an integer value as argument, which is causing compile time error.
The expectation is to create a custom class object with the testcase values of required class members and then to pass this object as argument. Please note that a constructor is available for this class.
Could you please let me know if I need to write anything in the .jpg file to handle custom class objects.

**Comment by ksluckow** [comment]
Yes, the test suite generator cannot automatically create instances for parameters. You can make it work if you wrap your test method in another method that only exposes primitive types that can be used for creating the object.

**Comment by zvonimir** [comment]
@srgiri If you are interested in generating custom class objects with JDart, I would suggest you also take a look at our JDoop project: https://github.com/psycopaths/jdoop

**Comment by srgiri** [comment]
@ksluckow and @zvonimir thank you.
