### ISSUE TITLE
How to test a method from diiferent java project in JDart.

### ISSUE THREAD

**Issue by srgiri** [psycopaths/jdart#25]
Hi,
  I have a java project _(say 'MyProj')_ with few classes and methods. The JDart project is configured separately. 
I want to test a method from MyProj. I can add/include MyProj into JDart in 'Build Path' setting of Eclipse.
The corresponding .jpf file is created inside JDart project. When run, it throws a message **cannot load application class .....**

It is not always possible to create classes inside JDart project. I may have some existing projects which might not be easy to copy inside JDart project. How can I test such projects ?

**Comment by ksluckow** [comment]
Hi!
JDart does not rely on any build paths you would set up in an IDE such as Eclipse; it solely relies on the configurations specified in `~/.jpf/site.properties`, `jpf.properties`[1] and "application jpf configuration files".
Therefore, if the SUT is not in `src/examples` or any of your JPF projects, you will have to explicitly update the classpath. In the jpf file, you do this by specifying the `classpath` variable, i.e.:
```
classpath=/classpath/to/your/SUT/
```

[1] jpf.properties files of JPF projects specified on the `extension` variable in `~/.jpf/site.properties` or by the `@using` directive.

**Comment by srgiri** [comment]
Thank you. It worked.
