### ISSUE TITLE
Outdated Docker file - docker build -t jdart . fails

### ISSUE THREAD

**Issue by zubair527** [psycopaths/jdart#32]
The babelfish.arc.nasa.gov server is not accessible publicly while the Dockerfile still tries to retrieve code from it. Which causes the failure in container initialization. See below extract from Dockerfile: 

    # Install jpf-core
    WORKDIR ${JDART_DIR}
    RUN hg clone http://babelfish.arc.nasa.gov/hg/jpf/jpf-core 
    # We know that rev 29 works with jdart
    WORKDIR ${JDART_DIR}/jpf-core
    RUN hg update -r 29
    RUN ant

**Comment by ksluckow** [comment]
Should be fixed now. Thanks!

**Comment by kfrajtak** [comment]
Hi, the docker build now fails with `E: Unable to locate package oracle-java8-installer`.

**Comment by shafirpl** [comment]
Is there any update to the fix ?

**Comment by samsbp** [comment]
i think that the project is not maintained so I fixed the issue here .https://github.com/samsbp/jdart
