### ISSUE TITLE
How to deal with the methods with no parameters yet could be affected by other methods? 

### ISSUE THREAD

**Issue by QRXqrx** [psycopaths/jdart#36]
Dear JDart community,

I'm using JDart these days and I just come up with a problem , that is, **how to deal a method with no parameters which could be affected by other methods with symbolic inputs**? Just like the following example. ``IncValue`` is the class under test. ``IncValue`` has two public methods:  ``incVal`` and ``examVal``. Method ``incVal`` requires a integer as input and ``examVal`` needs no param.
``` java
package simple.noparams;

/**
 *
 * Should we take method without parameters into account?
 * It depends on whether and how a method without parameters
 * are affected by symbolic values that passed in through
 * other methods with parameters.
 *
 * @author Adian
 */
public class IncValue {
    private int val = 1;
    public void incVal(int x) {
        this.val += x;
        if(x > 0)
            System.out.println("Larger val");
        else
            System.out.println("Smaller val");
    }
    public void examVal() {
        System.out.println("(val == x + 1)");
        if(this.val > 0)
            if(this.val < 10)
                System.out.println("(val > 0) && (val < 10)");
            else
                System.out.println("(val >= 10)");
        else
            if(this.val > -5)
                System.out.println("(val < 0) && (val > -5)");
            else
                System.out.println("(val <= -5");
    }
}
```

Now I want to use the test driver ``IncValueDriver1`` together with the jpf configurations below to executing ``IncValue``. I have noticed that JDart can only execute one method concolically (by set ``concolic.method=<target_method>``), thus I consider the method as the target method under test. Just as the examples shows, the execution of ``examVal`` cannot be effected directly from the test driver since it requires no parameter to run, though its execution can be indirectly affected by the value passed in through invoking ``incVal``. The ``x`` passed into ``incVal`` which will add the field ``val`` by ``x`` and turns out to effect the result of invoking ``examVal``. I'd like to get the path conditions of executing ``examVal`` when a symbolic value x is passed in by invoking ``incVal``. The path conditions I expected looks like ``((x+1) > 0) && ((x+1) < 10)``. 

Is there any possible way to implement this? I have noticed that there are some available settings for symbolic fields, (e.g. ``<prefix>.symbolic``), but I not sure how it works. It seems the ``this`` in example configurations refers to the instance of test driver, rather than the object (e.g. ``incValue`` in my example) created during the execution of test driver. I would appreciate it someone could help, please reply me at your convenience, thanks a lot 😄  !

```java
public class IncValueDriver1 {
    public static void main(String[] args) {
        IncValue incValue = new IncValue();
        incValue.incVal(5);
        incValue.examVal();
    }
}

```

Here is my configurations:
```
###############################################################################
#
# default jdart tools
#
# Some how like listeners for SPF and JPF
shell=gov.nasa.jpf.jdart.JDart
symbolic.dp=z3
symbolic.dp.z3.bitvectors=true

###############################################################################
#
# logging and jpf output
#
log.finest=jdart
log.info=constraints

### Common configs for IncValue
concolic.method.incVal=simple.noparams.IncValue.incVal(x:int)
concolic.method.incVal.config=incVal

concolic.method.examVal=simple.noparams.IncValue.examVal()
concolic.method.examVal.config=examVal

### Configs for IncValueDriver1

target=simple.noparams.IncValueDriver1
concolic.method=examVal

## Symbolize object fields
jdart.configs.all_fields_symbolic.symbolic.include=this.*
```

**Comment by QRXqrx** [comment]
Well, I successfully make ``IncValue.val`` symbolic through setting ``jdart.configs.examVal=this.*``, but the relation between the input symbolic params ``x`` and ``IncValue.val`` or ``this.val`` is still not clear. I guess this is because I can only set one method to be concolic executed through specifying ``concolic.method``.

**Comment by fhowar** [comment]
Hi, you could either write a slightly different test driver.

```java
public class IncValueDriver1 {

    public static void runTest(int x) {
        IncValue incValue = new IncValue();
        incValue.incVal(x);
        incValue.examVal();
    }

    public static void main(String[] args) {
        runTest(5);
    }
}
```

Now you can explore runTest(x) symbolically. Not sure if that is an option?

In the version of JDart we maintain at TU Dortmund, you can also make analyze main() and introduce symbolic values without explicit specification anywhere in the code by using ```Random.nextInt()```

You can check out current development version:
https://github.com/tudo-aqua/jdart

We have rewritten the constraints tree last year:
https://github.com/tudo-aqua/jdart/tree/sv-comp-2021/src/main/gov/nasa/jpf/jdart/constraints/tree

We are happy to provide support for the current version. Please ask a question here:
https://github.com/tudo-aqua/jdart/issues

**Comment by QRXqrx** [comment]
Hmmm... I still cannot extract the relation ship between ``x`` and ``this.val``, but it seems your idea enlightens me in another way.  After investigating JDart for couple of days, it seems I cannot use JDart to directly get the relationship yet maybe I could manipulate relations like this from outside. Thanks for your help! I will close this issue currently :-) !
