### ISSUE TITLE
[SEVERE] no static entry method: com.hsx.jpf.controller.JpfDemoPeopleController.main([Ljava/lang/String;)V

### ISSUE THREAD

**Issue by hsx1612727380** [psycopaths/jdart#37]

**Comment by fhowar** [comment]
Can you provide details? Code, Output, Jdart config?

**Comment by hsx1612727380** [comment]
Sorry, I didn't describe it.

The configuration is as follows：
1. site.properties
<img width="434" alt="image" src="https://user-images.githubusercontent.com/14011324/174767710-d9b17e45-41fe-44e7-8ed6-fe46d88c605f.png">
2. the UST(my project, not jdart) *.jpf
2.1 jpfUpdateAge.jpf
<img width="229" alt="image" src="https://user-images.githubusercontent.com/14011324/174768201-ddca15a1-eaf0-4527-ae87-d9d19f4cb23c.png">
2.2 example.jpf
<img width="738" alt="image" src="https://user-images.githubusercontent.com/14011324/174768363-4cab3cc6-0922-4bfc-902f-6e88edee235d.png">
2.3 jdart.jpf
<img width="675" alt="image" src="https://user-images.githubusercontent.com/14011324/174768500-36c1b5cb-3798-4603-a73d-9b8785092256.png">
3 *.java
<img width="581" alt="image" src="https://user-images.githubusercontent.com/14011324/174768722-4c1e881a-ef86-40d3-bc34-d4e743968728.png">

**Comment by fhowar** [comment]
Since JDart relies on execution of the SUT, you will need to add a ```main()``` method that executes the code/method you are interested in. 

However: Your example seems to be a SpringBoot controller with injected dependencies. To properly execute this example you would need to execute it by starting SpringBoot (to inject dependencies). JDart (or more precisely: the underlying JPF JVM) cannot do that since it is not a feature-complete JVM.

You could either just add the main and manually initialize the service manually (if that is sufficient for what you are interested in or have a look at GDart, which basically replaces the JPF VM in JDart with the GraalVM/espresso and is capable of executing SpringBoot test cases like the one you posted. 

Check out:

-  https://github.com/tudo-aqua/gdart-examples
- https://github.com/tudo-aqua/dse
- https://github.com/tudo-aqua/spout

**Comment by hsx1612727380** [comment]
Thank you very much.

I found that I really need to start SpringBoot and add a main().  It worked.

But，I want to know what good ways to support string？

**Comment by mmuesly** [comment]
Hi @hsx1612727380,

we do maintain version of JDart that supports strings at TU Dortmund university. Try to build this branch: https://github.com/tudo-aqua/jdart/tree/gradel_build

You will have to add `jdart.stringModel=SMTLibModel` to you jdart.jpf file, but it should work then. Let me know, if you have any further questions.

**Comment by hsx1612727380** [comment]
HI @mmuesly,

Thanks.

**Comment by hsx1612727380** [comment]
HI @mmuesly,

Thanks.

Currently, I am still studying jdart. If I have any other questions, I would like to ask you.

**Comment by BEbillionaireUSD** [comment]
> jdart.stringModel=SMTLibModel

I cannot build this version. It reports the following errors:
```
 > [35/35] RUN ant:
0.343 Buildfile: /jdart-project/jdart/build.xml
0.590
0.590 -init:
0.608
0.608 -compile-annotations:
0.610     [mkdir] Created dir: /jdart-project/jdart/build/annotations
0.623     [javac] Compiling 1 source file to /jdart-project/jdart/build/annotations
0.933
0.933 -compile-main:
0.933     [mkdir] Created dir: /jdart-project/jdart/build/main
0.975     [javac] Compiling 170 source files to /jdart-project/jdart/build/main
2.519     [javac] /jdart-project/jdart/src/main/gov/nasa/jpf/jdart/summaries/json/ExpressionHandler.java:61: error: unreported exception ImpreciseRepresentationException; must be caught or declared to be thrown
2.519     [javac]         return ParserUtil.parseArithmetic(s.substring(3));
2.519     [javac]                                          ^
2.519     [javac] /jdart-project/jdart/src/main/gov/nasa/jpf/jdart/summaries/json/ExpressionHandler.java:63: error: unreported exception ImpreciseRepresentationException; must be caught or declared to be thrown
2.519     [javac]       return ParserUtil.parseLogical(s.substring(3));
2.519     [javac]                                     ^
2.548     [javac] Note: Some input files use unchecked or unsafe operations.
2.548     [javac] Note: Recompile with -Xlint:unchecked for details.
2.549     [javac] 2 errors
2.553
2.553 BUILD FAILED
2.553 /jdart-project/jdart/build.xml:141: Compile failed; see the compiler error output for details.
2.553
2.553 Total time: 2 seconds
------

 5 warnings found (use docker --debug to expand):
 - MaintainerDeprecated: Maintainer instruction is deprecated in favor of using label (line 2)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 35)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 36)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 39)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 70)
Dockerfile:95
--------------------
  93 |     RUN git clone https://github.com/tudo-aqua/jdart.git
  94 |     WORKDIR ${JDART_DIR}/jdart
  95 | >>> RUN ant
  96 |
--------------------
ERROR: failed to solve: process "/bin/sh -c ant" did not complete successfully: exit code: 1

```
Could you please give me some help?
