### ISSUE TITLE
Problem with switch statement.

### ISSUE THREAD

**Issue by MarwenSami** [psycopaths/jdart#7]
Hello,
I noticed an ArrayIndexOutOfBoundsException that occurred on some "switch" statement, here is one of the buggy scripts:

```

        byte[] buffer = {(byte) 0x97, (byte) 0x10, (byte) 0xDE, (byte) 0x1E, (byte) 0xA0, (byte) 0x40, (byte) 0x31};
        byte cmptr = 0;

        switch(buffer[1]){
        case (byte) 0x00:
            cmptr++;
            break;
        case (byte) 0x01:
            cmptr--;
            break;
        case (byte) 0x02:
            buffer[0]=cmptr;
            break;  

        case (byte) 0x03:
            cmptr=buffer[5];
            break;
        default:
            System.err.println("We have a problem here");
        }


```

The exception: 

> Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
>   at gov.nasa.jpf.jdart.bytecode.TABLESWITCH.getTargetPC(TABLESWITCH.java:54)
>   at gov.nasa.jpf.jdart.bytecode.SwitchHelper.execute(SwitchHelper.java:60)
>   at gov.nasa.jpf.jdart.bytecode.TABLESWITCH.execute(TABLESWITCH.java:64)
>   at gov.nasa.jpf.vm.ThreadInfo.executeInstruction(ThreadInfo.java:1908)
>   at gov.nasa.jpf.vm.ThreadInfo.executeTransition(ThreadInfo.java:1859)
>   at gov.nasa.jpf.vm.SystemState.executeNextTransition(SystemState.java:765)
>   at gov.nasa.jpf.vm.VM.forward(VM.java:1722)
>   at gov.nasa.jpf.search.Search.forward(Search.java:579)
>   at gov.nasa.jpf.search.DFSearch.search(DFSearch.java:79)
>   at gov.nasa.jpf.JPF.run(JPF.java:613)
>   at gov.nasa.jpf.jdart.JDart.run(JDart.java:207)
>   at gov.nasa.jpf.jdart.JDart.start(JDart.java:131)
>   at gov.nasa.jpf.tool.RunJPF.main(RunJPF.java:108)

After trying to debug it I found out that the field "targetIdx gets value -1, so when it's passed to getTargetPC(int targetIdx) it raises the exception.
TABLESWITCH.lastIdx also equals -1.

**Comment by fhowar** [comment]
This is due to a bug in TABLESWITCH.java.

The fix is changing one method:

  @Override
  public int getTargetPC(int targetIdx) {
      if (targetIdx == DEFAULT) {
          return target;
      }
      return targets[targetIdx];
  }

I include an example for src/examples as well. 

[patch.tar.gz](https://github.com/psycopaths/jdart/files/410980/patch.tar.gz)

I cannot push the bug-fix currently. Maybe @ksluckow can fix it?

**Comment by MarwenSami** [comment]
Thanks for the fix,
Best regards,
